version: '3.8'
services:
  nginx:
    image: nginx:1.26
    platform: linux/arm64
    container_name: nginx-sqa
    ports:
      - "8080:80"
    volumes:
      - ./frontend/dist:/var/www/html
      - ./web/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask

  flask:
    build: ./backend
    image: flask-sqa
    container_name: flask-sqa
    # ports:
    #   - 5051:5000
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      - TZ=Asia/Tokyo
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:9.0
    platform: linux/arm64
    container_name: mysql-sqa
    # ports:
    #   - 3306:3306
    restart: always
    env_file:
      - ./db/.env
    environment:
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
